#ifndef _NMEA_H_
#define _NMEA_H_

#define NMEA_SENTENCE_LENGTH_MAX 82
#define NMEA_SENTENCE_NAME_LENGHT 5

#define NMEA_SENTENCE_START_DELIM '$'
#define NMEA_SENTENCE_PREFIX "GP"

#define NMEA_SENTENCE_GGA NMEA_SENTENCE_PREFIX ## "GGA"
#define NMEA_SENTENCE_GSA NMEA_SENTENCE_PREFIX ## "GSA"
#define NMEA_SENTENCE_GSV NMEA_SENTENCE_PREFIX ## "GSV"
#define NMEA_SENTENCE_RMC NMEA_SENTENCE_PREFIX ## "RMC"
#define NMEA_SENTENCE_VTG NMEA_SENTENCE_PREFIX ## "VTG"


#endif